### ISSUE TITLE
make notifications translatable 

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/notification#5]
(e.g. notification text to be stored per language)

E.g. notification has many 
notificationTranslation
notificationId
languageId
... <Notification transatable field>
...<Notification transatable field>
...<Notification transatable field>

**Comment by John1s** [comment]
When creating a new notification you must now include at least 1 translation. The users preferred language is looked up from their profile and the appropriate translation applied for that user. 
If there is no translation for their preferred language the default language is used. The default language can be defined when creating the notification by setting an "isDefault" field to true on that translation.
