### ISSUE TITLE
Allow status for user per notification

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/notification#6]
change schema that allows bulk notifications to be dismissed per user (e.g. notification 2 user link with status)

e.g. notification hasMany
UserNotification
notificationId
userId
status  (active, dismissed, maybe more)
emailStatus (skip, sent, bounced, opened)

**Comment by John1s** [comment]
There is an endpoint for a a user to get all their unseen notifications. Their is another endpoint for the user to acknowledge that they have seen the notification, which sets the status to dismissed.
