### ISSUE TITLE
Implement email sending of notifications

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/notification#7]
implement email sending for all recepients of a notification in their preferred language

This means for all recepients of a notificaiton we need to trigger email sending.
Figure out whether to enhance email service to take advantage of mailjet options (contact list, bulk send via template)

Or whether to follow one email per recepient as we do in e.g. onboarding.

Make sure we send email notificaiton in user preferred language.

**Comment by John1s** [comment]
All recepients of a notification will now be emailed in their preferred language. 
One email is sent out per recepient. The service creates seperate events per user to allow the translating and sending of emails to be scaled over several services. This makes the bulk sending of emails impractical. If we require bulk sending in the future we will need a design change.
