### ISSUE TITLE
CRUD editor for notifications

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/notification#9]
create UI for creating new notifications (CRUD editor)

Allow to create new
- enter text in each language
- enter category (maybe from enum)
- enter subject and other notificaiton fields per language

Allow saving only when all languages are filled
Allow copy from other language or define fallback

**Comment by John1s** [comment]
This is over 1 year old and I don't think this is still valid. Notifications are in many cases immediately sent as emails. To allow the text to be edited would have no effect. 
Any changes should be sent as new notifications.
